name: Build Documentation

on:
 push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: windows-latest

    steps:
    # Checkout all repos
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Setup dotnet
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 5.0.x

    - name: Setup DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx

    - name: Build docs
      run: docfx Alibi.Plugins.API/docfx/docfx.json

    # Publish generated site using GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: Alibi.Plugins.API/docfx/_site # The folder the action should deploy.