name: Build Documentation

on:
 push:
    branches:
      - main
    paths:
      - .github/**
      - Alibi.Plugins.API/**

jobs:
  build-docs:
    runs-on: windows-latest

    steps:
    # Checkout all repos
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Setup dotnet
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 5.0.x

    - name: Setup DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx

    - name: Build docs
      run: |
        docfx metadata Alibi.Plugins.API/docfx/docfx.json
        docfx build Alibi.Plugins.API/docfx/docfx.json
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: Alibi.Plugins.API/docfx/_site

  deploy-docs:
    needs: [build-docs] # The second job must depend on the first one to complete before running, and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: "docs"