name: Build Documentation

on:
 push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    # Checkout all repos
    - name: Checkout repo
      uses: actions/checkout@v1

    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: Alibi.Plugins.API/docfx/docfx.json

    # Publish generated site using GitHub Pages
    - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: Alibi.Plugins.API/docfx/_site # The folder the action should deploy.